heat-test_geotimedata:
  geopoint_field: location
  idx: test_geotimedata
  mode: heat
  timestamp_field: '@timestamp'
category-test_geotimedata:
  idx: test_geotimedata
  category_field: country.keyword
  mode: category
  geopoint_field: location
  timestamp_field: '@timestamp'
