[tool.poetry]
name = "elastic_datashader"
version = "0.0.5"
description = "Elastic-Datashader TMS Server"
authors = ["Spectric Labs <foss@spectric.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/spectriclabs/elastic_datashader"
classifiers = [
	"Topic :: Scientific/Engineering :: GIS",
	"Topic :: Scientific/Engineering :: Information Analysis",
	"Topic :: Scientific/Engineering :: Visualization"
]

[tool.poetry.scripts]
elastic_datashader = "elastic_datashader.cli:main"

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
Flask = ">=2"
elasticsearch = ">=7.16"
elasticsearch-dsl = ">=7.4"
pyOpenSSL = ">=21"
datashader = ">=0.11.0"
pandas = ">=1.2.0"
colorcet = ">=3.0.0"
mercantile = ">=1.2.1"
pypng = ">=0.0.21"
Flask-APScheduler = ">=1.12"
Pillow = ">=9"
pynumeral = ">=0.1.2"
arrow = ">=1.2"
python-datemath = ">=1.5"
numba = ">=0.48"
numpy = ">=1.19"
urllib3 = ">=1.26"
PyYAML = ">=6.0"
gunicorn = {version = ">=20.1.0", optional = true}
humanize = ">=3"

[tool.poetry.dev-dependencies]
pytest = ">=6"
pytest-cov = ">=3"
black = ">=21.12b0"
pylint = ">=2"

[tool.poetry.extras]
apm = ["elasticapm"]
localwebserver = ["gunicorn"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
